name: x86-Windows-llvm-from-sources

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download Ninja
        shell: cmake -P {0}
        run: |
          # The following steps are implemented using CMake commands
          set(ninja_version "1.9.0")
          set(ninja_suffix "windows.zip")
          set(ninja_url "https://github.com/ninja-build/ninja/releases/download/v${ninja_version}/ninja-${ninja_suffix}")
          file(DOWNLOAD "${ninja_url}" ./ninja.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ninja.zip)
          if (NOT "${{ runner.os }}" STREQUAL "Windows")
            execute_process(
            COMMAND chmod +x ninja
            )
          endif()
          
      - name: Install choco
        run: |
          choco install -y ninja git cmake gnuwin python3 make
          pip3 install pygments yaml 
          
      - name: Build LLVM
        run: |
          # Adding the location of Ninja to $PATH
          $env:Path += "$;GITHUB_WORKSPACE"
          git clone --depth 1 https://github.com/d3xter-lab/llvm-obfuscator /tmp/llvm-obfuscator
          cd /tmp/llvm-obfuscator
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=_install -DLLVM_TARGETS_TO_BUILD=host ..
